# Generated by Django 3.2.14 on 2022-07-25 18:57
import os.path
import uuid

from PIL import Image, ImageOps

from django.db import migrations
from django.conf import settings
import recipe_db.fields
import recipe_db.models


def convert_recipe_image_to_webp(apps, schema_editor):
    RecipeImageModel = apps.get_model('recipe_db', 'RecipeImage')
    for recipe_image in RecipeImageModel.objects.all():
        if not recipe_image.image.name.endswith("webp"):
            old_path = recipe_image.image.path
            image_name_split = list(os.path.split(recipe_image.image.name))
            image_name_split[-1] = f"{uuid.uuid4().hex}.webp"
            new_name = os.path.join(*image_name_split)
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)
            image = Image.open(old_path)
            image = ImageOps.exif_transpose(image)
            image.save(fp=new_path, format="WEBP")
            recipe_image.image.name = new_name
            recipe_image.save()
            os.remove(old_path)



class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0004_move_recipe_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=recipe_db.fields.WebPField(upload_to=recipe_db.models.generate_image_path),
        ),
        migrations.RunPython(convert_recipe_image_to_webp, reverse_code=migrations.RunPython.noop),
    ]
