# Generated by Django 3.2.14 on 2022-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0005_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_plan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
