# Generated by Django 3.2.14 on 2022-07-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0006_add_thumbnail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_plan',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
