# Generated by Django 3.2.14 on 2022-07-25 21:06

import os

from PIL import Image

from django.db import migrations
from django.conf import settings


def generate_thumbnails_for_recipe_images(apps, schema_editor):
    RecipeImageModel = apps.get_model('recipe_db', 'RecipeImage')
    for recipe_image in RecipeImageModel.objects.all():
        if not recipe_image.thumbnail_card and not recipe_image.thumbnail_plan:
            image_name = recipe_image.image.name
            image_name, _ = os.path.splitext(image_name)
            thumbnail_card = Image.open(recipe_image.image.path)
            thumbnail_plan = thumbnail_card.copy()
            thumbnail_card = crop_image_to_aspect(thumbnail_card, 448. / 224.)
            thumbnail_card.thumbnail((448, 224), Image.BICUBIC)
            thumbnail_plan = crop_image_to_aspect(thumbnail_plan, 112. / 128.)
            thumbnail_plan.thumbnail((112, 128), Image.BICUBIC)
            thumbnail_card_name = f"{image_name}_thumb_card.webp"
            thumbnail_card_path = os.path.join(settings.MEDIA_ROOT, thumbnail_card_name)
            thumbnail_card.save(fp=thumbnail_card_path, format="WEBP")
            recipe_image.thumbnail_card.name = thumbnail_card_name
            thumbnail_plan_name = f"{image_name}_thumb_plan.webp"
            thumbnail_plan_path = os.path.join(settings.MEDIA_ROOT, thumbnail_plan_name)
            thumbnail_plan.save(fp=thumbnail_plan_path, format="WEBP")
            recipe_image.thumbnail_plan.name = thumbnail_plan_name
            recipe_image.save()


def crop_image_to_aspect(image: Image, aspect: float) -> Image:
    if image.width / image.height > aspect:
        new_width = int(image.height * aspect)
        new_height = image.height
    else:
        new_width = image.width
        new_height = int(image.width / aspect)
    return image.crop((
        0.5 * (image.width - new_width),
        0.5 * (image.height - new_height),
        0.5 * (image.width - new_width) + new_width,
        0.5 * (image.height - new_height) + new_height
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0007_thumbnails_not_editable'),
    ]

    operations = [
        migrations.RunPython(generate_thumbnails_for_recipe_images),
    ]
