# Generated by Django 3.2.14 on 2022-07-26 19:04

from django.db import migrations, models
import recipe_db.fields
import recipe_db.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0008_gen_thumbnails_for_recipe_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='image_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='image_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_card_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_card_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_plan_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='thumbnail_plan_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=recipe_db.fields.WebPField(height_field='image_height', upload_to=recipe_db.models.generate_image_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_card',
            field=models.ImageField(blank=True, editable=False, height_field='thumbnail_card_height', null=True, upload_to='', width_field='thumbnail_card_width'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_plan',
            field=models.ImageField(blank=True, editable=False, height_field='thumbnail_plan_height', null=True, upload_to='', width_field='thumbnail_plan_width'),
        ),
    ]
