# Generated by Django 3.2.14 on 2022-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0009_add_recipe_image_size_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_card_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_card_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_plan_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='thumbnail_plan_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
