# Generated by Django 3.2.14 on 2022-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0010_allow_null_recipe_thumbnail_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_text',
            field=models.TextField(blank=True),
        ),
    ]
