# Generated by Django 3.2.14 on 2022-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0012_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='p256dh_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
