# Generated by Django 3.2.14 on 2022-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0013_pushsubscription_p256dh_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(unique=True),
        ),
    ]
