# Generated by Django 3.2.15 on 2022-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0014_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='notify_at_new_recipes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
