# Generated by Django 3.2.15 on 2022-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0015_pushsubscription_notify_at_new_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
