version: "3"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - ./postgres_data/data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${RECIPE_DB_POSTGRES_PASSWORD}
    network_mode: host
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backup_data:/home/app/web/backup_data
    environment:
      - POSTGRES_NAME=postgres_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${RECIPE_DB_POSTGRES_PASSWORD}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=fRGVjNTaymiywXEMUAlpHch7a6A4bL5FYvWm3vqysbduKnmcJ1zzuDFjqmJp
      - DJANGO_DEBUG=true
      - DJANGO_ALLOWED_HOST=${RECIPE_DB_ALLOWED_HOST}
      - DJANGO_VAPID_PRIVATE_KEY=${RECIPE_DB_VAPID_PRIVATE_KEY}
      - DJANGO_MAIL_ADDRESS="git@heidenblut.eu"
    network_mode: host
    depends_on:
      - db

volumes:
  postgres_data:
  backup_data: